/*
Copyright wbsnail.com.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/wbsnail/articles/archive/dive-into-kubernetes-informer/11-crd-informer/apis/stable.wbsnail.com/v1"
	scheme "github.com/wbsnail/articles/archive/dive-into-kubernetes-informer/11-crd-informer/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RabbitsGetter has a method to return a RabbitInterface.
// A group's client should implement this interface.
type RabbitsGetter interface {
	Rabbits(namespace string) RabbitInterface
}

// RabbitInterface has methods to work with Rabbit resources.
type RabbitInterface interface {
	Create(ctx context.Context, rabbit *v1.Rabbit, opts metav1.CreateOptions) (*v1.Rabbit, error)
	Update(ctx context.Context, rabbit *v1.Rabbit, opts metav1.UpdateOptions) (*v1.Rabbit, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Rabbit, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RabbitList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Rabbit, err error)
	RabbitExpansion
}

// rabbits implements RabbitInterface
type rabbits struct {
	client rest.Interface
	ns     string
}

// newRabbits returns a Rabbits
func newRabbits(c *StableV1Client, namespace string) *rabbits {
	return &rabbits{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rabbit, and returns the corresponding rabbit object, and an error if there is any.
func (c *rabbits) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Rabbit, err error) {
	result = &v1.Rabbit{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rabbits").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Rabbits that match those selectors.
func (c *rabbits) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RabbitList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RabbitList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rabbits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rabbits.
func (c *rabbits) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rabbits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rabbit and creates it.  Returns the server's representation of the rabbit, and an error, if there is any.
func (c *rabbits) Create(ctx context.Context, rabbit *v1.Rabbit, opts metav1.CreateOptions) (result *v1.Rabbit, err error) {
	result = &v1.Rabbit{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rabbits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rabbit).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rabbit and updates it. Returns the server's representation of the rabbit, and an error, if there is any.
func (c *rabbits) Update(ctx context.Context, rabbit *v1.Rabbit, opts metav1.UpdateOptions) (result *v1.Rabbit, err error) {
	result = &v1.Rabbit{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rabbits").
		Name(rabbit.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rabbit).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rabbit and deletes it. Returns an error if one occurs.
func (c *rabbits) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rabbits").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rabbits) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rabbits").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rabbit.
func (c *rabbits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Rabbit, err error) {
	result = &v1.Rabbit{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rabbits").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
