apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbits.stable.wbsnail.com
spec:
  group: stable.wbsnail.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
    additionalPrinterColumns:
    - name: Color
      type: string
      description: Color
      jsonPath: .spec.color
    - name: Age
      type: date
      description: Age
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: rabbits
    singular: rabbit
    kind: Rabbit
